# Generated by Django 5.1.6 on 2025-03-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('BIOGRAPHY', 'Biography'), ('ROMANS', 'Romans'), ('POETRY', 'Poetry')], default='FICTION', max_length=255),
        ),
    ]
